### ISSUE TITLE
z-nomp for fabcoin

### ISSUE THREAD

**Issue by fsql** [blockchaingate/fabcoin#12]
`2018-07-26 10:39:50 [POSIX]	[Connection Limit] (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
2018-07-26 10:39:50 [Master]	[CLI] CLI listening on port 17117
2018-07-26 10:39:50 [PPLNT]	[fabcoin] TimeShare processing setup with redis (127.0.0.1:6379)
2018-07-26 10:39:51 [Master]	[PoolSpawner] Spawned 1 pool(s) on 2 thread(s)
2018-07-26 10:39:51 [Website]	[Server] Website started on 0.0.0.0:80
2018-07-26 10:39:51 [Switching]	[Setup] (Thread 1) Loading last proxy state from redis
2018-07-26 10:39:52 [Pool]	[fabcoin] (Thread 1) Share processing setup with redis (127.0.0.1:6379)

/root/fabpool/pool/node_modules/typeforce/index.js:159
          throw tfSubError(e, i)
          ^
Error: Expected property "1" of type Satoshi, got Number 249250000000015040
    at tfSubError (/root/fabpool/pool/node_modules/typeforce/errors.js:93:9)
    at /root/fabpool/pool/node_modules/typeforce/index.js:159:17
    at Array.every (native)
    at _tuple (/root/fabpool/pool/node_modules/typeforce/index.js:155:20)
    at typeforce (/root/fabpool/pool/node_modules/typeforce/index.js:196:9)
    at Transaction.addOutput (/root/fabpool/pool/node_modules/bitcoinjs-lib-zcash/src/transaction.js:297:3)
    at Object.exports.createGeneration (/root/fabpool/pool/node_modules/stratum-pool/lib/transactions.js:118:12)
    at new BlockTemplate (/root/fabpool/pool/node_modules/stratum-pool/lib/blockTemplate.js:43:35)
    at JobManager.processTemplate (/root/fabpool/pool/node_modules/stratum-pool/lib/jobManager.js:150:32)
    at /root/fabpool/pool/node_modules/stratum-pool/lib/pool.js:588:66
2018-07-26 10:39:52 [Master]	[PoolSpawner] Fork 0 died, spawning replacement worker...
2018-07-26 10:39:52 [Switching]	[Setup] (Thread 2) Loading last proxy state from redis
2018-07-26 10:39:52 [Pool]	[fabcoin] (Thread 2) Share processing setup with redis (127.0.0.1:6379)`

Do you know which file needs to be edited?
@blockchaingate

**Comment by blockchaingate** [comment]
Sorry, I have no experience with z-nomp.
